### PR TITLE
PO(T) Export, for message extraction

### PR DESCRIPTION
**Pull request by TropicalPenguin**
Permits the writing of message extractors, using gotext. With round-tripping support to update existing translations (while preserving contextual details like copyright notices & source references).

### CODE REVIEW

**Comment by leonelquinteros** [comment]
@TropicalPenguin  Thanks for your contribution. 

Please note that there are some conflicts after I merged a previous PR I had pending. 
Can you also review the changes included in the last PR ( https://github.com/leonelquinteros/gotext/pull/44 ) and adapt your feature to the new code? I think we can benefit from both together.

**Comment by TropicalPenguin** [comment]
Yeah, no problem; got a few more improvements to make anyway.

**Comment by TropicalPenguin** [comment]
I think that should do it :smile:

**Comment by leonelquinteros** [comment]
Thank you @TropicalPenguin  !

**Pull request merged**
